// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketFlowApi.Data;

#nullable disable

namespace TicketFlowApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111011708_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "priority", new[] { "low", "mid", "high" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "step", new[] { "open", "in_analysis", "in_development", "in_tests", "paused", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketFlowApi.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1496),
                            Description = "Área de suporte técnico",
                            Name = "Suporte"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1522),
                            Description = "Área financeira",
                            Name = "Financeiro"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1546),
                            Description = "Recursos Humanos",
                            Name = "RH"
                        });
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("CallCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1618),
                            Description = "Problemas de hardware",
                            Name = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1642),
                            Description = "Problemas de software",
                            Name = "Software"
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1666),
                            Description = "Problemas de rede",
                            Name = "Rede"
                        },
                        new
                        {
                            Id = 4,
                            AreaId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1690),
                            Description = "Gestão de pagamentos",
                            Name = "Contas a pagar"
                        },
                        new
                        {
                            Id = 5,
                            AreaId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1713),
                            Description = "Gestão de recebimentos",
                            Name = "Contas a receber"
                        },
                        new
                        {
                            Id = 6,
                            AreaId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1739),
                            Description = "Relatórios financeiros",
                            Name = "Relatórios"
                        },
                        new
                        {
                            Id = 7,
                            AreaId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1762),
                            Description = "Processo seletivo",
                            Name = "Recrutamento"
                        },
                        new
                        {
                            Id = 8,
                            AreaId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1786),
                            Description = "Pagamentos de funcionários",
                            Name = "Folha de pagamento"
                        },
                        new
                        {
                            Id = 9,
                            AreaId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1809),
                            Description = "Capacitação e treinamentos",
                            Name = "Treinamento"
                        });
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CalledId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOpen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonForClosing")
                        .HasColumnType("text");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestionAI")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CalledId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("CallMetadata");
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CallSubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1997),
                            Description = "Problemas com notebooks",
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2021),
                            Description = "Problemas com desktops",
                            Name = "Desktop"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2046),
                            Description = "Problemas com impressoras",
                            Name = "Impressora"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2070),
                            Description = "Problemas com ERP",
                            Name = "ERP"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2094),
                            Description = "Problemas com sistemas internos",
                            Name = "Sistema interno"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2118),
                            Description = "Problemas com aplicativos",
                            Name = "Aplicativo"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2141),
                            Description = "Problemas com Wi-Fi",
                            Name = "Wi-Fi"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2163),
                            Description = "Problemas com VPN",
                            Name = "VPN"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2184),
                            Description = "Problemas com firewall",
                            Name = "Firewall"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2209),
                            Description = "Emissão de faturas",
                            Name = "Faturas"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2232),
                            Description = "Gestão de pagamentos agendados",
                            Name = "Pagamentos agendados"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2255),
                            Description = "Controle de despesas",
                            Name = "Despesas"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2280),
                            Description = "Controle de recebimentos",
                            Name = "Recebimentos"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2304),
                            Description = "Cobrança de clientes",
                            Name = "Cobrança"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2324),
                            Description = "Controle de NF",
                            Name = "Notas fiscais"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2349),
                            Description = "Criação de balancetes",
                            Name = "Balancete"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2373),
                            Description = "Controle de fluxo de caixa",
                            Name = "Fluxo de caixa"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2398),
                            Description = "Relatórios financeiros",
                            Name = "Relatórios mensais"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2422),
                            Description = "Entrevistas de candidatos",
                            Name = "Entrevista"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2445),
                            Description = "Testes de candidatos",
                            Name = "Teste técnico"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2468),
                            Description = "Dinâmicas de grupo",
                            Name = "Dinâmica de grupo"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2492),
                            Description = "Controle de salários",
                            Name = "Salários"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2515),
                            Description = "Gestão de benefícios",
                            Name = "Benefícios"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2539),
                            Description = "Controle de férias",
                            Name = "Férias"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2563),
                            Description = "Treinamentos internos",
                            Name = "Cursos internos"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2586),
                            Description = "Workshops de capacitação",
                            Name = "Workshops"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(2610),
                            Description = "Webinars de treinamento",
                            Name = "Webinars"
                        });
                });

            modelBuilder.Entity("TicketFlowApi.Models.Called", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidencePath")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Calleds");
                });

            modelBuilder.Entity("TicketFlowApi.Models.LogsCalled", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ByUser")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovedFrom")
                        .HasColumnType("integer");

                    b.Property<int>("MovedTo")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LogsCalled");
                });

            modelBuilder.Entity("TicketFlowApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(978),
                            Email = "joedoe@example.com",
                            Password = "password",
                            Role = "admin",
                            UpdatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(992),
                            Username = "Joe Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1062),
                            Email = "janedoe@example.com",
                            Password = "password",
                            Role = "normal",
                            UpdatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1076),
                            Username = "Jane Doe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1124),
                            Email = "thaysadoe@example.com",
                            Password = "password",
                            Role = "normal",
                            UpdatedAt = new DateTime(2025, 11, 11, 1, 17, 8, 22, DateTimeKind.Utc).AddTicks(1137),
                            Username = "Thaysa Doe"
                        });
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallCategory", b =>
                {
                    b.HasOne("TicketFlowApi.Models.Area", "Area")
                        .WithMany("Categories")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallMetadata", b =>
                {
                    b.HasOne("TicketFlowApi.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketFlowApi.Models.User", "AssignedUser")
                        .WithMany("AssignedCalls")
                        .HasForeignKey("AssignedUserId");

                    b.HasOne("TicketFlowApi.Models.Called", "Called")
                        .WithOne("CallMetadata")
                        .HasForeignKey("TicketFlowApi.Models.CallMetadata", "CalledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketFlowApi.Models.CallCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketFlowApi.Models.CallSubCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("AssignedUser");

                    b.Navigation("Called");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallSubCategory", b =>
                {
                    b.HasOne("TicketFlowApi.Models.CallCategory", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TicketFlowApi.Models.Called", b =>
                {
                    b.HasOne("TicketFlowApi.Models.User", "User")
                        .WithMany("Calleds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlowApi.Models.LogsCalled", b =>
                {
                    b.HasOne("TicketFlowApi.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketFlowApi.Models.Area", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("TicketFlowApi.Models.CallCategory", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("TicketFlowApi.Models.Called", b =>
                {
                    b.Navigation("CallMetadata");
                });

            modelBuilder.Entity("TicketFlowApi.Models.User", b =>
                {
                    b.Navigation("AssignedCalls");

                    b.Navigation("Calleds");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
